var annotated_dup =
[
    [ "bort", "namespacebort.html", [
      [ "ast", "namespacebort_1_1ast.html", [
        [ "detail", "namespacebort_1_1ast_1_1detail.html", [
          [ "TypePairHasher", "structbort_1_1ast_1_1detail_1_1TypePairHasher.html", "structbort_1_1ast_1_1detail_1_1TypePairHasher" ]
        ] ],
        [ "ASTDebugInfo", "structbort_1_1ast_1_1ASTDebugInfo.html", "structbort_1_1ast_1_1ASTDebugInfo" ],
        [ "ASTPrinter", "classbort_1_1ast_1_1ASTPrinter.html", null ],
        [ "ASTRoot", "classbort_1_1ast_1_1ASTRoot.html", "classbort_1_1ast_1_1ASTRoot" ],
        [ "ASTVisitorBase", "classbort_1_1ast_1_1ASTVisitorBase.html", "classbort_1_1ast_1_1ASTVisitorBase" ],
        [ "BinOpExpr", "classbort_1_1ast_1_1BinOpExpr.html", "classbort_1_1ast_1_1BinOpExpr" ],
        [ "Block", "classbort_1_1ast_1_1Block.html", "classbort_1_1ast_1_1Block" ],
        [ "BreakStmt", "classbort_1_1ast_1_1BreakStmt.html", "classbort_1_1ast_1_1BreakStmt" ],
        [ "ContinueStmt", "classbort_1_1ast_1_1ContinueStmt.html", "classbort_1_1ast_1_1ContinueStmt" ],
        [ "ExpressionNode", "classbort_1_1ast_1_1ExpressionNode.html", "classbort_1_1ast_1_1ExpressionNode" ],
        [ "ExpressionStmt", "classbort_1_1ast_1_1ExpressionStmt.html", "classbort_1_1ast_1_1ExpressionStmt" ],
        [ "FatalSemanticError", "classbort_1_1ast_1_1FatalSemanticError.html", "classbort_1_1ast_1_1FatalSemanticError" ],
        [ "FunctionCallExpr", "classbort_1_1ast_1_1FunctionCallExpr.html", "classbort_1_1ast_1_1FunctionCallExpr" ],
        [ "FunctionDecl", "classbort_1_1ast_1_1FunctionDecl.html", "classbort_1_1ast_1_1FunctionDecl" ],
        [ "IfStmt", "classbort_1_1ast_1_1IfStmt.html", "classbort_1_1ast_1_1IfStmt" ],
        [ "IndexationExpr", "classbort_1_1ast_1_1IndexationExpr.html", "classbort_1_1ast_1_1IndexationExpr" ],
        [ "InitializerList", "classbort_1_1ast_1_1InitializerList.html", "classbort_1_1ast_1_1InitializerList" ],
        [ "Node", "classbort_1_1ast_1_1Node.html", "classbort_1_1ast_1_1Node" ],
        [ "NodeSubstitutionVisitor", "classbort_1_1ast_1_1NodeSubstitutionVisitor.html", null ],
        [ "NumberExpr", "classbort_1_1ast_1_1NumberExpr.html", "classbort_1_1ast_1_1NumberExpr" ],
        [ "ReturnStmt", "classbort_1_1ast_1_1ReturnStmt.html", "classbort_1_1ast_1_1ReturnStmt" ],
        [ "Scope", "classbort_1_1ast_1_1Scope.html", "classbort_1_1ast_1_1Scope" ],
        [ "Statement", "classbort_1_1ast_1_1Statement.html", "classbort_1_1ast_1_1Statement" ],
        [ "StructureAwareASTVisitor", "classbort_1_1ast_1_1StructureAwareASTVisitor.html", "classbort_1_1ast_1_1StructureAwareASTVisitor" ],
        [ "SymbolAlreadyDefinedError", "classbort_1_1ast_1_1SymbolAlreadyDefinedError.html", "classbort_1_1ast_1_1SymbolAlreadyDefinedError" ],
        [ "SymbolResolutionVisitor", "classbort_1_1ast_1_1SymbolResolutionVisitor.html", "classbort_1_1ast_1_1SymbolResolutionVisitor" ],
        [ "TypePropagationVisitor", "classbort_1_1ast_1_1TypePropagationVisitor.html", "classbort_1_1ast_1_1TypePropagationVisitor" ],
        [ "UnaryOpExpr", "classbort_1_1ast_1_1UnaryOpExpr.html", "classbort_1_1ast_1_1UnaryOpExpr" ],
        [ "VarDecl", "classbort_1_1ast_1_1VarDecl.html", "classbort_1_1ast_1_1VarDecl" ],
        [ "VariableExpr", "classbort_1_1ast_1_1VariableExpr.html", "classbort_1_1ast_1_1VariableExpr" ],
        [ "WhileStmt", "classbort_1_1ast_1_1WhileStmt.html", "classbort_1_1ast_1_1WhileStmt" ]
      ] ],
      [ "codegen", "namespacebort_1_1codegen.html", [
        [ "rv", "namespacebort_1_1codegen_1_1rv.html", [
          [ "FrameOffset", "structbort_1_1codegen_1_1rv_1_1FrameOffset.html", "structbort_1_1codegen_1_1rv_1_1FrameOffset" ],
          [ "Generator", "classbort_1_1codegen_1_1rv_1_1Generator.html", "classbort_1_1codegen_1_1rv_1_1Generator" ],
          [ "InstructionChoicePass", "classbort_1_1codegen_1_1rv_1_1InstructionChoicePass.html", null ],
          [ "MemoryDependencyMDTag", "structbort_1_1codegen_1_1rv_1_1MemoryDependencyMDTag.html", "structbort_1_1codegen_1_1rv_1_1MemoryDependencyMDTag" ],
          [ "PreprocessPass", "classbort_1_1codegen_1_1rv_1_1PreprocessPass.html", null ],
          [ "Printer", "classbort_1_1codegen_1_1rv_1_1Printer.html", "classbort_1_1codegen_1_1rv_1_1Printer" ],
          [ "RARSMacroCallInst", "classbort_1_1codegen_1_1rv_1_1RARSMacroCallInst.html", "classbort_1_1codegen_1_1rv_1_1RARSMacroCallInst" ],
          [ "RARSMacroDefinitions", "structbort_1_1codegen_1_1rv_1_1RARSMacroDefinitions.html", "structbort_1_1codegen_1_1rv_1_1RARSMacroDefinitions" ],
          [ "RVBranchInfo", "structbort_1_1codegen_1_1rv_1_1RVBranchInfo.html", "structbort_1_1codegen_1_1rv_1_1RVBranchInfo" ],
          [ "RVFuncPrologueEpilogue", "structbort_1_1codegen_1_1rv_1_1RVFuncPrologueEpilogue.html", "structbort_1_1codegen_1_1rv_1_1RVFuncPrologueEpilogue" ],
          [ "RVInstInfo", "structbort_1_1codegen_1_1rv_1_1RVInstInfo.html", "structbort_1_1codegen_1_1rv_1_1RVInstInfo" ],
          [ "RVMachineRegister", "classbort_1_1codegen_1_1rv_1_1RVMachineRegister.html", "classbort_1_1codegen_1_1rv_1_1RVMachineRegister" ],
          [ "RVOpAdditionalInfo", "structbort_1_1codegen_1_1rv_1_1RVOpAdditionalInfo.html", "structbort_1_1codegen_1_1rv_1_1RVOpAdditionalInfo" ],
          [ "StoreSourceOperandMD", "classbort_1_1codegen_1_1rv_1_1StoreSourceOperandMD.html", "classbort_1_1codegen_1_1rv_1_1StoreSourceOperandMD" ]
        ] ],
        [ "FrameInfo", "classbort_1_1codegen_1_1FrameInfo.html", "classbort_1_1codegen_1_1FrameInfo" ],
        [ "InstructionRemover", "classbort_1_1codegen_1_1InstructionRemover.html", "classbort_1_1codegen_1_1InstructionRemover" ],
        [ "InstructionVisitorBase", "classbort_1_1codegen_1_1InstructionVisitorBase.html", "classbort_1_1codegen_1_1InstructionVisitorBase" ],
        [ "MachineRegister", "classbort_1_1codegen_1_1MachineRegister.html", "classbort_1_1codegen_1_1MachineRegister" ],
        [ "RegisterLoc", "classbort_1_1codegen_1_1RegisterLoc.html", "classbort_1_1codegen_1_1RegisterLoc" ],
        [ "RemoveInstructionMDTag", "structbort_1_1codegen_1_1RemoveInstructionMDTag.html", "structbort_1_1codegen_1_1RemoveInstructionMDTag" ],
        [ "StackLoc", "classbort_1_1codegen_1_1StackLoc.html", "classbort_1_1codegen_1_1StackLoc" ],
        [ "ValueLoc", "classbort_1_1codegen_1_1ValueLoc.html", "classbort_1_1codegen_1_1ValueLoc" ]
      ] ],
      [ "exceptions", "namespacebort_1_1exceptions.html", [
        [ "SourceFileFailedToOpen", "classbort_1_1exceptions_1_1SourceFileFailedToOpen.html", "classbort_1_1exceptions_1_1SourceFileFailedToOpen" ],
        [ "SourceFileInvalidExtension", "classbort_1_1exceptions_1_1SourceFileInvalidExtension.html", "classbort_1_1exceptions_1_1SourceFileInvalidExtension" ],
        [ "SourceFileReaderError", "classbort_1_1exceptions_1_1SourceFileReaderError.html", "classbort_1_1exceptions_1_1SourceFileReaderError" ]
      ] ],
      [ "ir", "namespacebort_1_1ir.html", [
        [ "AllocaInst", "classbort_1_1ir_1_1AllocaInst.html", "classbort_1_1ir_1_1AllocaInst" ],
        [ "BasicBlock", "classbort_1_1ir_1_1BasicBlock.html", "classbort_1_1ir_1_1BasicBlock" ],
        [ "BranchInst", "classbort_1_1ir_1_1BranchInst.html", "classbort_1_1ir_1_1BranchInst" ],
        [ "BrToLoopEndMDTag", "structbort_1_1ir_1_1BrToLoopEndMDTag.html", "structbort_1_1ir_1_1BrToLoopEndMDTag" ],
        [ "BrToLoopStartMDTag", "structbort_1_1ir_1_1BrToLoopStartMDTag.html", "structbort_1_1ir_1_1BrToLoopStartMDTag" ],
        [ "CallInst", "classbort_1_1ir_1_1CallInst.html", "classbort_1_1ir_1_1CallInst" ],
        [ "Constant", "structbort_1_1ir_1_1Constant.html", "structbort_1_1ir_1_1Constant" ],
        [ "GepInst", "classbort_1_1ir_1_1GepInst.html", "classbort_1_1ir_1_1GepInst" ],
        [ "GlobalArray", "classbort_1_1ir_1_1GlobalArray.html", "classbort_1_1ir_1_1GlobalArray" ],
        [ "GlobalValue", "classbort_1_1ir_1_1GlobalValue.html", "classbort_1_1ir_1_1GlobalValue" ],
        [ "Instruction", "classbort_1_1ir_1_1Instruction.html", "classbort_1_1ir_1_1Instruction" ],
        [ "IntegralConstant", "classbort_1_1ir_1_1IntegralConstant.html", "classbort_1_1ir_1_1IntegralConstant" ],
        [ "IRCodegen", "classbort_1_1ir_1_1IRCodegen.html", "classbort_1_1ir_1_1IRCodegen" ],
        [ "IRFunction", "classbort_1_1ir_1_1IRFunction.html", "classbort_1_1ir_1_1IRFunction" ],
        [ "IRPrinter", "classbort_1_1ir_1_1IRPrinter.html", "classbort_1_1ir_1_1IRPrinter" ],
        [ "LoadInst", "classbort_1_1ir_1_1LoadInst.html", "classbort_1_1ir_1_1LoadInst" ],
        [ "MDList", "classbort_1_1ir_1_1MDList.html", "classbort_1_1ir_1_1MDList" ],
        [ "MDTag", "classbort_1_1ir_1_1MDTag.html", "classbort_1_1ir_1_1MDTag" ],
        [ "Metadata", "structbort_1_1ir_1_1Metadata.html", "structbort_1_1ir_1_1Metadata" ],
        [ "Module", "classbort_1_1ir_1_1Module.html", "classbort_1_1ir_1_1Module" ],
        [ "MoveInst", "classbort_1_1ir_1_1MoveInst.html", "classbort_1_1ir_1_1MoveInst" ],
        [ "Operand", "classbort_1_1ir_1_1Operand.html", "classbort_1_1ir_1_1Operand" ],
        [ "OpInst", "classbort_1_1ir_1_1OpInst.html", "classbort_1_1ir_1_1OpInst" ],
        [ "Register", "classbort_1_1ir_1_1Register.html", null ],
        [ "RetInst", "classbort_1_1ir_1_1RetInst.html", "classbort_1_1ir_1_1RetInst" ],
        [ "StoreInst", "classbort_1_1ir_1_1StoreInst.html", "classbort_1_1ir_1_1StoreInst" ],
        [ "StoreSync", "classbort_1_1ir_1_1StoreSync.html", "classbort_1_1ir_1_1StoreSync" ],
        [ "TraversalContext", "structbort_1_1ir_1_1TraversalContext.html", "structbort_1_1ir_1_1TraversalContext" ],
        [ "UnaryInst", "classbort_1_1ir_1_1UnaryInst.html", "classbort_1_1ir_1_1UnaryInst" ],
        [ "Value", "classbort_1_1ir_1_1Value.html", "classbort_1_1ir_1_1Value" ],
        [ "VariableUse", "classbort_1_1ir_1_1VariableUse.html", "classbort_1_1ir_1_1VariableUse" ]
      ] ],
      [ "ArrayType", "classbort_1_1ArrayType.html", "classbort_1_1ArrayType" ],
      [ "BackendFatalError", "structbort_1_1BackendFatalError.html", null ],
      [ "BackendInstance", "classbort_1_1BackendInstance.html", "classbort_1_1BackendInstance" ],
      [ "CharType", "classbort_1_1CharType.html", "classbort_1_1CharType" ],
      [ "CLIOptions", "classbort_1_1CLIOptions.html", "classbort_1_1CLIOptions" ],
      [ "Diagnostic", "classbort_1_1Diagnostic.html", "classbort_1_1Diagnostic" ],
      [ "FrontEndFatalError", "classbort_1_1FrontEndFatalError.html", "classbort_1_1FrontEndFatalError" ],
      [ "FrontEndInstance", "structbort_1_1FrontEndInstance.html", "structbort_1_1FrontEndInstance" ],
      [ "Function", "classbort_1_1Function.html", "classbort_1_1Function" ],
      [ "IntType", "classbort_1_1IntType.html", "classbort_1_1IntType" ],
      [ "Lexer", "classbort_1_1Lexer.html", "classbort_1_1Lexer" ],
      [ "LexerFatalError", "classbort_1_1LexerFatalError.html", "classbort_1_1LexerFatalError" ],
      [ "MiddleEndInstance", "classbort_1_1MiddleEndInstance.html", "classbort_1_1MiddleEndInstance" ],
      [ "Parser", "classbort_1_1Parser.html", "classbort_1_1Parser" ],
      [ "PointerType", "classbort_1_1PointerType.html", "classbort_1_1PointerType" ],
      [ "Preprocessor", "classbort_1_1Preprocessor.html", "classbort_1_1Preprocessor" ],
      [ "SourceFile", "classbort_1_1SourceFile.html", "classbort_1_1SourceFile" ],
      [ "SourceFileInfo", "structbort_1_1SourceFileInfo.html", "structbort_1_1SourceFileInfo" ],
      [ "SourceFileIt", "classbort_1_1SourceFileIt.html", "classbort_1_1SourceFileIt" ],
      [ "Symbol", "classbort_1_1Symbol.html", "classbort_1_1Symbol" ],
      [ "Token", "classbort_1_1Token.html", "classbort_1_1Token" ],
      [ "Type", "classbort_1_1Type.html", "classbort_1_1Type" ],
      [ "TypeRefHasher", "structbort_1_1TypeRefHasher.html", "structbort_1_1TypeRefHasher" ],
      [ "Variable", "classbort_1_1Variable.html", "classbort_1_1Variable" ],
      [ "VisitDispatcher", "classbort_1_1VisitDispatcher.html", null ],
      [ "VisitorTraits", "structbort_1_1VisitorTraits.html", null ],
      [ "VisitorTraits< bort::codegen::InstructionVisitorBase >", "structbort_1_1VisitorTraits_3_01bort_1_1codegen_1_1InstructionVisitorBase_01_4.html", null ],
      [ "VisitorTraits< IRPrinter >", "structbort_1_1VisitorTraits_3_01IRPrinter_01_4.html", null ],
      [ "VoidType", "classbort_1_1VoidType.html", "classbort_1_1VoidType" ]
    ] ],
    [ "GlobalValueInitializerFormatter", "structGlobalValueInitializerFormatter.html", "structGlobalValueInitializerFormatter" ]
];