var annotated_dup =
[
    [ "bort", "namespacebort.html", [
      [ "ast", "namespacebort_1_1ast.html", [
        [ "detail", "namespacebort_1_1ast_1_1detail.html", [
          [ "TypePairHasher", "structbort_1_1ast_1_1detail_1_1TypePairHasher.html", "structbort_1_1ast_1_1detail_1_1TypePairHasher" ]
        ] ],
        [ "ASTDebugInfo", "structbort_1_1ast_1_1ASTDebugInfo.html", "structbort_1_1ast_1_1ASTDebugInfo" ],
        [ "ASTPrinter", "classbort_1_1ast_1_1ASTPrinter.html", null ],
        [ "ASTRoot", "classbort_1_1ast_1_1ASTRoot.html", "classbort_1_1ast_1_1ASTRoot" ],
        [ "ASTVisitorBase", "classbort_1_1ast_1_1ASTVisitorBase.html", "classbort_1_1ast_1_1ASTVisitorBase" ],
        [ "BinOpExpr", "classbort_1_1ast_1_1BinOpExpr.html", "classbort_1_1ast_1_1BinOpExpr" ],
        [ "Block", "classbort_1_1ast_1_1Block.html", "classbort_1_1ast_1_1Block" ],
        [ "ExpressionNode", "classbort_1_1ast_1_1ExpressionNode.html", "classbort_1_1ast_1_1ExpressionNode" ],
        [ "ExpressionStmt", "classbort_1_1ast_1_1ExpressionStmt.html", "classbort_1_1ast_1_1ExpressionStmt" ],
        [ "FunctionCallExpr", "classbort_1_1ast_1_1FunctionCallExpr.html", "classbort_1_1ast_1_1FunctionCallExpr" ],
        [ "FunctionDecl", "classbort_1_1ast_1_1FunctionDecl.html", "classbort_1_1ast_1_1FunctionDecl" ],
        [ "IfStmt", "classbort_1_1ast_1_1IfStmt.html", "classbort_1_1ast_1_1IfStmt" ],
        [ "Node", "classbort_1_1ast_1_1Node.html", "classbort_1_1ast_1_1Node" ],
        [ "NumberExpr", "classbort_1_1ast_1_1NumberExpr.html", "classbort_1_1ast_1_1NumberExpr" ],
        [ "ReturnStmt", "classbort_1_1ast_1_1ReturnStmt.html", "classbort_1_1ast_1_1ReturnStmt" ],
        [ "Scope", "classbort_1_1ast_1_1Scope.html", "classbort_1_1ast_1_1Scope" ],
        [ "Statement", "classbort_1_1ast_1_1Statement.html", "classbort_1_1ast_1_1Statement" ],
        [ "StructureAwareASTVisitor", "classbort_1_1ast_1_1StructureAwareASTVisitor.html", "classbort_1_1ast_1_1StructureAwareASTVisitor" ],
        [ "SymbolAlreadyDefinedError", "classbort_1_1ast_1_1SymbolAlreadyDefinedError.html", "classbort_1_1ast_1_1SymbolAlreadyDefinedError" ],
        [ "SymbolResolutionVisitor", "classbort_1_1ast_1_1SymbolResolutionVisitor.html", "classbort_1_1ast_1_1SymbolResolutionVisitor" ],
        [ "TypePropagationVisitor", "classbort_1_1ast_1_1TypePropagationVisitor.html", "classbort_1_1ast_1_1TypePropagationVisitor" ],
        [ "VarDecl", "classbort_1_1ast_1_1VarDecl.html", "classbort_1_1ast_1_1VarDecl" ],
        [ "VariableExpr", "classbort_1_1ast_1_1VariableExpr.html", "classbort_1_1ast_1_1VariableExpr" ],
        [ "WhileStmt", "classbort_1_1ast_1_1WhileStmt.html", "classbort_1_1ast_1_1WhileStmt" ]
      ] ],
      [ "codegen", "namespacebort_1_1codegen.html", [
        [ "rv", "namespacebort_1_1codegen_1_1rv.html", [
          [ "FrameOffset", "structbort_1_1codegen_1_1rv_1_1FrameOffset.html", "structbort_1_1codegen_1_1rv_1_1FrameOffset" ],
          [ "Generator", "classbort_1_1codegen_1_1rv_1_1Generator.html", "classbort_1_1codegen_1_1rv_1_1Generator" ],
          [ "InstructionChoiceVisitor", "classbort_1_1codegen_1_1rv_1_1InstructionChoiceVisitor.html", null ],
          [ "PreprocessVisitor", "classbort_1_1codegen_1_1rv_1_1PreprocessVisitor.html", null ],
          [ "Printer", "classbort_1_1codegen_1_1rv_1_1Printer.html", "classbort_1_1codegen_1_1rv_1_1Printer" ],
          [ "RVFuncPrologueEpilogue", "structbort_1_1codegen_1_1rv_1_1RVFuncPrologueEpilogue.html", "structbort_1_1codegen_1_1rv_1_1RVFuncPrologueEpilogue" ],
          [ "RVInstInfo", "structbort_1_1codegen_1_1rv_1_1RVInstInfo.html", "structbort_1_1codegen_1_1rv_1_1RVInstInfo" ],
          [ "RVMachineRegister", "classbort_1_1codegen_1_1rv_1_1RVMachineRegister.html", "classbort_1_1codegen_1_1rv_1_1RVMachineRegister" ]
        ] ],
        [ "FrameInfo", "classbort_1_1codegen_1_1FrameInfo.html", "classbort_1_1codegen_1_1FrameInfo" ],
        [ "InstructionVisitorBase", "classbort_1_1codegen_1_1InstructionVisitorBase.html", "classbort_1_1codegen_1_1InstructionVisitorBase" ],
        [ "LoadInst", "classbort_1_1codegen_1_1LoadInst.html", "classbort_1_1codegen_1_1LoadInst" ],
        [ "MachineRegister", "classbort_1_1codegen_1_1MachineRegister.html", "classbort_1_1codegen_1_1MachineRegister" ],
        [ "RegisterLoc", "classbort_1_1codegen_1_1RegisterLoc.html", "classbort_1_1codegen_1_1RegisterLoc" ],
        [ "StackLoc", "classbort_1_1codegen_1_1StackLoc.html", "classbort_1_1codegen_1_1StackLoc" ],
        [ "StoreInst", "classbort_1_1codegen_1_1StoreInst.html", "classbort_1_1codegen_1_1StoreInst" ],
        [ "ValueLoc", "classbort_1_1codegen_1_1ValueLoc.html", "classbort_1_1codegen_1_1ValueLoc" ]
      ] ],
      [ "exceptions", "namespacebort_1_1exceptions.html", [
        [ "SourceFileFailedToOpen", "classbort_1_1exceptions_1_1SourceFileFailedToOpen.html", "classbort_1_1exceptions_1_1SourceFileFailedToOpen" ],
        [ "SourceFileInvalidExtension", "classbort_1_1exceptions_1_1SourceFileInvalidExtension.html", "classbort_1_1exceptions_1_1SourceFileInvalidExtension" ],
        [ "SourceFileReaderError", "classbort_1_1exceptions_1_1SourceFileReaderError.html", "classbort_1_1exceptions_1_1SourceFileReaderError" ]
      ] ],
      [ "ir", "namespacebort_1_1ir.html", [
        [ "AllocaInst", "classbort_1_1ir_1_1AllocaInst.html", "classbort_1_1ir_1_1AllocaInst" ],
        [ "BasicBlock", "classbort_1_1ir_1_1BasicBlock.html", "classbort_1_1ir_1_1BasicBlock" ],
        [ "BranchInst", "classbort_1_1ir_1_1BranchInst.html", "classbort_1_1ir_1_1BranchInst" ],
        [ "CallInst", "classbort_1_1ir_1_1CallInst.html", "classbort_1_1ir_1_1CallInst" ],
        [ "Constant", "structbort_1_1ir_1_1Constant.html", "structbort_1_1ir_1_1Constant" ],
        [ "Instruction", "classbort_1_1ir_1_1Instruction.html", "classbort_1_1ir_1_1Instruction" ],
        [ "IntConstant", "classbort_1_1ir_1_1IntConstant.html", "classbort_1_1ir_1_1IntConstant" ],
        [ "IRCodegen", "classbort_1_1ir_1_1IRCodegen.html", "classbort_1_1ir_1_1IRCodegen" ],
        [ "IRFunction", "classbort_1_1ir_1_1IRFunction.html", "classbort_1_1ir_1_1IRFunction" ],
        [ "IRPrinter", "classbort_1_1ir_1_1IRPrinter.html", "classbort_1_1ir_1_1IRPrinter" ],
        [ "MDList", "classbort_1_1ir_1_1MDList.html", "classbort_1_1ir_1_1MDList" ],
        [ "Metadata", "structbort_1_1ir_1_1Metadata.html", "structbort_1_1ir_1_1Metadata" ],
        [ "Module", "classbort_1_1ir_1_1Module.html", "classbort_1_1ir_1_1Module" ],
        [ "MoveInst", "classbort_1_1ir_1_1MoveInst.html", "classbort_1_1ir_1_1MoveInst" ],
        [ "Operand", "classbort_1_1ir_1_1Operand.html", "classbort_1_1ir_1_1Operand" ],
        [ "OpInst", "classbort_1_1ir_1_1OpInst.html", "classbort_1_1ir_1_1OpInst" ],
        [ "Register", "classbort_1_1ir_1_1Register.html", null ],
        [ "RetInst", "classbort_1_1ir_1_1RetInst.html", "classbort_1_1ir_1_1RetInst" ],
        [ "Value", "classbort_1_1ir_1_1Value.html", "classbort_1_1ir_1_1Value" ],
        [ "VariableUse", "classbort_1_1ir_1_1VariableUse.html", null ]
      ] ],
      [ "ArrayType", "classbort_1_1ArrayType.html", "classbort_1_1ArrayType" ],
      [ "CharType", "classbort_1_1CharType.html", "classbort_1_1CharType" ],
      [ "CLIOptions", "classbort_1_1CLIOptions.html", "classbort_1_1CLIOptions" ],
      [ "Diagnostic", "classbort_1_1Diagnostic.html", "classbort_1_1Diagnostic" ],
      [ "FrontEndFatalError", "classbort_1_1FrontEndFatalError.html", "classbort_1_1FrontEndFatalError" ],
      [ "FrontEndInstance", "structbort_1_1FrontEndInstance.html", "structbort_1_1FrontEndInstance" ],
      [ "Function", "classbort_1_1Function.html", "classbort_1_1Function" ],
      [ "IntType", "classbort_1_1IntType.html", "classbort_1_1IntType" ],
      [ "Lexer", "classbort_1_1Lexer.html", "classbort_1_1Lexer" ],
      [ "LexerFatalError", "classbort_1_1LexerFatalError.html", "classbort_1_1LexerFatalError" ],
      [ "MiddleEndInstance", "classbort_1_1MiddleEndInstance.html", "classbort_1_1MiddleEndInstance" ],
      [ "Parser", "classbort_1_1Parser.html", "classbort_1_1Parser" ],
      [ "PointerType", "classbort_1_1PointerType.html", "classbort_1_1PointerType" ],
      [ "Preprocessor", "classbort_1_1Preprocessor.html", "classbort_1_1Preprocessor" ],
      [ "SourceFile", "classbort_1_1SourceFile.html", "classbort_1_1SourceFile" ],
      [ "SourceFileInfo", "structbort_1_1SourceFileInfo.html", "structbort_1_1SourceFileInfo" ],
      [ "SourceFileIt", "classbort_1_1SourceFileIt.html", "classbort_1_1SourceFileIt" ],
      [ "Symbol", "classbort_1_1Symbol.html", "classbort_1_1Symbol" ],
      [ "Token", "classbort_1_1Token.html", "classbort_1_1Token" ],
      [ "Type", "classbort_1_1Type.html", "classbort_1_1Type" ],
      [ "TypeRefHasher", "structbort_1_1TypeRefHasher.html", "structbort_1_1TypeRefHasher" ],
      [ "Variable", "classbort_1_1Variable.html", "classbort_1_1Variable" ],
      [ "VoidType", "classbort_1_1VoidType.html", "classbort_1_1VoidType" ]
    ] ]
];